<?php

/*
 * Default functions
 */

if ( ! defined( 'ABSPATH' ) )
    exit ; // Exit if accessed directly.

if ( ! function_exists( 'get_esf_currencies' ) ) {

    /**
     * Get full list of currency codes.
     */
    function get_esf_currencies() {
        static $currencies ;

        if ( ! isset( $currencies ) ) {
            $currencies = array_unique(
                    apply_filters(
                            'esf_currencies' , array(
                'AED' => esc_html__( 'United Arab Emirates dirham' , ESF_LOCALE ) ,
                'AFN' => esc_html__( 'Afghan afghani' , ESF_LOCALE ) ,
                'ALL' => esc_html__( 'Albanian lek' , ESF_LOCALE ) ,
                'AMD' => esc_html__( 'Armenian dram' , ESF_LOCALE ) ,
                'ANG' => esc_html__( 'Netherlands Antillean guilder' , ESF_LOCALE ) ,
                'AOA' => esc_html__( 'Angolan kwanza' , ESF_LOCALE ) ,
                'ARS' => esc_html__( 'Argentine peso' , ESF_LOCALE ) ,
                'AUD' => esc_html__( 'Australian dollar' , ESF_LOCALE ) ,
                'AWG' => esc_html__( 'Aruban florin' , ESF_LOCALE ) ,
                'AZN' => esc_html__( 'Azerbaijani manat' , ESF_LOCALE ) ,
                'BAM' => esc_html__( 'Bosnia and Herzegovina convertible mark' , ESF_LOCALE ) ,
                'BBD' => esc_html__( 'Barbadian dollar' , ESF_LOCALE ) ,
                'BDT' => esc_html__( 'Bangladeshi taka' , ESF_LOCALE ) ,
                'BGN' => esc_html__( 'Bulgarian lev' , ESF_LOCALE ) ,
                'BHD' => esc_html__( 'Bahraini dinar' , ESF_LOCALE ) ,
                'BIF' => esc_html__( 'Burundian franc' , ESF_LOCALE ) ,
                'BMD' => esc_html__( 'Bermudian dollar' , ESF_LOCALE ) ,
                'BND' => esc_html__( 'Brunei dollar' , ESF_LOCALE ) ,
                'BOB' => esc_html__( 'Bolivian boliviano' , ESF_LOCALE ) ,
                'BRL' => esc_html__( 'Brazilian real' , ESF_LOCALE ) ,
                'BSD' => esc_html__( 'Bahamian dollar' , ESF_LOCALE ) ,
                'BTC' => esc_html__( 'Bitcoin' , ESF_LOCALE ) ,
                'BTN' => esc_html__( 'Bhutanese ngultrum' , ESF_LOCALE ) ,
                'BWP' => esc_html__( 'Botswana pula' , ESF_LOCALE ) ,
                'BYR' => esc_html__( 'Belarusian ruble (old)' , ESF_LOCALE ) ,
                'BYN' => esc_html__( 'Belarusian ruble' , ESF_LOCALE ) ,
                'BZD' => esc_html__( 'Belize dollar' , ESF_LOCALE ) ,
                'CAD' => esc_html__( 'Canadian dollar' , ESF_LOCALE ) ,
                'CDF' => esc_html__( 'Congolese franc' , ESF_LOCALE ) ,
                'CHF' => esc_html__( 'Swiss franc' , ESF_LOCALE ) ,
                'CLP' => esc_html__( 'Chilean peso' , ESF_LOCALE ) ,
                'CNY' => esc_html__( 'Chinese yuan' , ESF_LOCALE ) ,
                'COP' => esc_html__( 'Colombian peso' , ESF_LOCALE ) ,
                'CRC' => esc_html__( 'Costa Rican col&oacute;n' , ESF_LOCALE ) ,
                'CUC' => esc_html__( 'Cuban convertible peso' , ESF_LOCALE ) ,
                'CUP' => esc_html__( 'Cuban peso' , ESF_LOCALE ) ,
                'CVE' => esc_html__( 'Cape Verdean escudo' , ESF_LOCALE ) ,
                'CZK' => esc_html__( 'Czech koruna' , ESF_LOCALE ) ,
                'DJF' => esc_html__( 'Djiboutian franc' , ESF_LOCALE ) ,
                'DKK' => esc_html__( 'Danish krone' , ESF_LOCALE ) ,
                'DOP' => esc_html__( 'Dominican peso' , ESF_LOCALE ) ,
                'DZD' => esc_html__( 'Algerian dinar' , ESF_LOCALE ) ,
                'EGP' => esc_html__( 'Egyptian pound' , ESF_LOCALE ) ,
                'ERN' => esc_html__( 'Eritrean nakfa' , ESF_LOCALE ) ,
                'ETB' => esc_html__( 'Ethiopian birr' , ESF_LOCALE ) ,
                'EUR' => esc_html__( 'Euro' , ESF_LOCALE ) ,
                'FJD' => esc_html__( 'Fijian dollar' , ESF_LOCALE ) ,
                'FKP' => esc_html__( 'Falkland Islands pound' , ESF_LOCALE ) ,
                'GBP' => esc_html__( 'Pound sterling' , ESF_LOCALE ) ,
                'GEL' => esc_html__( 'Georgian lari' , ESF_LOCALE ) ,
                'GGP' => esc_html__( 'Guernsey pound' , ESF_LOCALE ) ,
                'GHS' => esc_html__( 'Ghana cedi' , ESF_LOCALE ) ,
                'GIP' => esc_html__( 'Gibraltar pound' , ESF_LOCALE ) ,
                'GMD' => esc_html__( 'Gambian dalasi' , ESF_LOCALE ) ,
                'GNF' => esc_html__( 'Guinean franc' , ESF_LOCALE ) ,
                'GTQ' => esc_html__( 'Guatemalan quetzal' , ESF_LOCALE ) ,
                'GYD' => esc_html__( 'Guyanese dollar' , ESF_LOCALE ) ,
                'HKD' => esc_html__( 'Hong Kong dollar' , ESF_LOCALE ) ,
                'HNL' => esc_html__( 'Honduran lempira' , ESF_LOCALE ) ,
                'HRK' => esc_html__( 'Croatian kuna' , ESF_LOCALE ) ,
                'HTG' => esc_html__( 'Haitian gourde' , ESF_LOCALE ) ,
                'HUF' => esc_html__( 'Hungarian forint' , ESF_LOCALE ) ,
                'IDR' => esc_html__( 'Indonesian rupiah' , ESF_LOCALE ) ,
                'ILS' => esc_html__( 'Israeli new shekel' , ESF_LOCALE ) ,
                'IMP' => esc_html__( 'Manx pound' , ESF_LOCALE ) ,
                'INR' => esc_html__( 'Indian rupee' , ESF_LOCALE ) ,
                'IQD' => esc_html__( 'Iraqi dinar' , ESF_LOCALE ) ,
                'IRR' => esc_html__( 'Iranian rial' , ESF_LOCALE ) ,
                'IRT' => esc_html__( 'Iranian toman' , ESF_LOCALE ) ,
                'ISK' => esc_html__( 'Icelandic kr&oacute;na' , ESF_LOCALE ) ,
                'JEP' => esc_html__( 'Jersey pound' , ESF_LOCALE ) ,
                'JMD' => esc_html__( 'Jamaican dollar' , ESF_LOCALE ) ,
                'JOD' => esc_html__( 'Jordanian dinar' , ESF_LOCALE ) ,
                'JPY' => esc_html__( 'Japanese yen' , ESF_LOCALE ) ,
                'KES' => esc_html__( 'Kenyan shilling' , ESF_LOCALE ) ,
                'KGS' => esc_html__( 'Kyrgyzstani som' , ESF_LOCALE ) ,
                'KHR' => esc_html__( 'Cambodian riel' , ESF_LOCALE ) ,
                'KMF' => esc_html__( 'Comorian franc' , ESF_LOCALE ) ,
                'KPW' => esc_html__( 'North Korean won' , ESF_LOCALE ) ,
                'KRW' => esc_html__( 'South Korean won' , ESF_LOCALE ) ,
                'KWD' => esc_html__( 'Kuwaiti dinar' , ESF_LOCALE ) ,
                'KYD' => esc_html__( 'Cayman Islands dollar' , ESF_LOCALE ) ,
                'KZT' => esc_html__( 'Kazakhstani tenge' , ESF_LOCALE ) ,
                'LAK' => esc_html__( 'Lao kip' , ESF_LOCALE ) ,
                'LBP' => esc_html__( 'Lebanese pound' , ESF_LOCALE ) ,
                'LKR' => esc_html__( 'Sri Lankan rupee' , ESF_LOCALE ) ,
                'LRD' => esc_html__( 'Liberian dollar' , ESF_LOCALE ) ,
                'LSL' => esc_html__( 'Lesotho loti' , ESF_LOCALE ) ,
                'LYD' => esc_html__( 'Libyan dinar' , ESF_LOCALE ) ,
                'MAD' => esc_html__( 'Moroccan dirham' , ESF_LOCALE ) ,
                'MDL' => esc_html__( 'Moldovan leu' , ESF_LOCALE ) ,
                'MGA' => esc_html__( 'Malagasy ariary' , ESF_LOCALE ) ,
                'MKD' => esc_html__( 'Macedonian denar' , ESF_LOCALE ) ,
                'MMK' => esc_html__( 'Burmese kyat' , ESF_LOCALE ) ,
                'MNT' => esc_html__( 'Mongolian t&ouml;gr&ouml;g' , ESF_LOCALE ) ,
                'MOP' => esc_html__( 'Macanese pataca' , ESF_LOCALE ) ,
                'MRO' => esc_html__( 'Mauritanian ouguiya' , ESF_LOCALE ) ,
                'MUR' => esc_html__( 'Mauritian rupee' , ESF_LOCALE ) ,
                'MVR' => esc_html__( 'Maldivian rufiyaa' , ESF_LOCALE ) ,
                'MWK' => esc_html__( 'Malawian kwacha' , ESF_LOCALE ) ,
                'MXN' => esc_html__( 'Mexican peso' , ESF_LOCALE ) ,
                'MYR' => esc_html__( 'Malaysian ringgit' , ESF_LOCALE ) ,
                'MZN' => esc_html__( 'Mozambican metical' , ESF_LOCALE ) ,
                'NAD' => esc_html__( 'Namibian dollar' , ESF_LOCALE ) ,
                'NGN' => esc_html__( 'Nigerian naira' , ESF_LOCALE ) ,
                'NIO' => esc_html__( 'Nicaraguan c&oacute;rdoba' , ESF_LOCALE ) ,
                'NOK' => esc_html__( 'Norwegian krone' , ESF_LOCALE ) ,
                'NPR' => esc_html__( 'Nepalese rupee' , ESF_LOCALE ) ,
                'NZD' => esc_html__( 'New Zealand dollar' , ESF_LOCALE ) ,
                'OMR' => esc_html__( 'Omani rial' , ESF_LOCALE ) ,
                'PAB' => esc_html__( 'Panamanian balboa' , ESF_LOCALE ) ,
                'PEN' => esc_html__( 'Peruvian nuevo sol' , ESF_LOCALE ) ,
                'PGK' => esc_html__( 'Papua New Guinean kina' , ESF_LOCALE ) ,
                'PHP' => esc_html__( 'Philippine peso' , ESF_LOCALE ) ,
                'PKR' => esc_html__( 'Pakistani rupee' , ESF_LOCALE ) ,
                'PLN' => esc_html__( 'Polish z&#x142;oty' , ESF_LOCALE ) ,
                'PRB' => esc_html__( 'Transnistrian ruble' , ESF_LOCALE ) ,
                'PYG' => esc_html__( 'Paraguayan guaran&iacute;' , ESF_LOCALE ) ,
                'QAR' => esc_html__( 'Qatari riyal' , ESF_LOCALE ) ,
                'RON' => esc_html__( 'Romanian leu' , ESF_LOCALE ) ,
                'RSD' => esc_html__( 'Serbian dinar' , ESF_LOCALE ) ,
                'RUB' => esc_html__( 'Russian ruble' , ESF_LOCALE ) ,
                'RWF' => esc_html__( 'Rwandan franc' , ESF_LOCALE ) ,
                'SAR' => esc_html__( 'Saudi riyal' , ESF_LOCALE ) ,
                'SBD' => esc_html__( 'Solomon Islands dollar' , ESF_LOCALE ) ,
                'SCR' => esc_html__( 'Seychellois rupee' , ESF_LOCALE ) ,
                'SDG' => esc_html__( 'Sudanese pound' , ESF_LOCALE ) ,
                'SEK' => esc_html__( 'Swedish krona' , ESF_LOCALE ) ,
                'SGD' => esc_html__( 'Singapore dollar' , ESF_LOCALE ) ,
                'SHP' => esc_html__( 'Saint Helena pound' , ESF_LOCALE ) ,
                'SLL' => esc_html__( 'Sierra Leonean leone' , ESF_LOCALE ) ,
                'SOS' => esc_html__( 'Somali shilling' , ESF_LOCALE ) ,
                'SRD' => esc_html__( 'Surinamese dollar' , ESF_LOCALE ) ,
                'SSP' => esc_html__( 'South Sudanese pound' , ESF_LOCALE ) ,
                'STD' => esc_html__( 'S&atilde;o Tom&eacute; and Pr&iacute;ncipe dobra' , ESF_LOCALE ) ,
                'SYP' => esc_html__( 'Syrian pound' , ESF_LOCALE ) ,
                'SZL' => esc_html__( 'Swazi lilangeni' , ESF_LOCALE ) ,
                'THB' => esc_html__( 'Thai baht' , ESF_LOCALE ) ,
                'TJS' => esc_html__( 'Tajikistani somoni' , ESF_LOCALE ) ,
                'TMT' => esc_html__( 'Turkmenistan manat' , ESF_LOCALE ) ,
                'TND' => esc_html__( 'Tunisian dinar' , ESF_LOCALE ) ,
                'TOP' => esc_html__( 'Tongan pa&#x2bb;anga' , ESF_LOCALE ) ,
                'TRY' => esc_html__( 'Turkish lira' , ESF_LOCALE ) ,
                'TTD' => esc_html__( 'Trinidad and Tobago dollar' , ESF_LOCALE ) ,
                'TWD' => esc_html__( 'New Taiwan dollar' , ESF_LOCALE ) ,
                'TZS' => esc_html__( 'Tanzanian shilling' , ESF_LOCALE ) ,
                'UAH' => esc_html__( 'Ukrainian hryvnia' , ESF_LOCALE ) ,
                'UGX' => esc_html__( 'Ugandan shilling' , ESF_LOCALE ) ,
                'USD' => esc_html__( 'United States (US) dollar' , ESF_LOCALE ) ,
                'UYU' => esc_html__( 'Uruguayan peso' , ESF_LOCALE ) ,
                'UZS' => esc_html__( 'Uzbekistani som' , ESF_LOCALE ) ,
                'VEF' => esc_html__( 'Venezuelan bol&iacute;var' , ESF_LOCALE ) ,
                'VND' => esc_html__( 'Vietnamese &#x111;&#x1ed3;ng' , ESF_LOCALE ) ,
                'VUV' => esc_html__( 'Vanuatu vatu' , ESF_LOCALE ) ,
                'WST' => esc_html__( 'Samoan t&#x101;l&#x101;' , ESF_LOCALE ) ,
                'XAF' => esc_html__( 'Central African CFA franc' , ESF_LOCALE ) ,
                'XCD' => esc_html__( 'East Caribbean dollar' , ESF_LOCALE ) ,
                'XOF' => esc_html__( 'West African CFA franc' , ESF_LOCALE ) ,
                'XPF' => esc_html__( 'CFP franc' , ESF_LOCALE ) ,
                'YER' => esc_html__( 'Yemeni rial' , ESF_LOCALE ) ,
                'ZAR' => esc_html__( 'South African rand' , ESF_LOCALE ) ,
                'ZMW' => esc_html__( 'Zambian kwacha' , ESF_LOCALE ) ,
                            )
                    )
                    ) ;
        }

        return $currencies ;
    }

}

if ( ! function_exists( 'get_esf_currency' ) ) {

    /**
     * Get site currency.
     */
    function get_esf_currency() {
        $currency = get_option( 'esf_currency' , 'USD' ) ;

        return apply_filters( 'esf_get_curreny' , $currency ) ;
    }

}

if ( ! function_exists( 'get_esf_currency_symbol' ) ) {

    function get_esf_currency_symbol( $currency = '' ) {
        if ( ! $currency ) {
            $currency = get_esf_currency() ;
        }

        $symbols         = apply_filters(
                'esf_currency_symbols' , array(
            'AED' => '&#x62f;.&#x625;' ,
            'AFN' => '&#x60b;' ,
            'ALL' => 'L' ,
            'AMD' => 'AMD' ,
            'ANG' => '&fnof;' ,
            'AOA' => 'Kz' ,
            'ARS' => '&#36;' ,
            'AUD' => '&#36;' ,
            'AWG' => 'Afl.' ,
            'AZN' => 'AZN' ,
            'BAM' => 'KM' ,
            'BBD' => '&#36;' ,
            'BDT' => '&#2547;&nbsp;' ,
            'BGN' => '&#1083;&#1074;.' ,
            'BHD' => '.&#x62f;.&#x628;' ,
            'BIF' => 'Fr' ,
            'BMD' => '&#36;' ,
            'BND' => '&#36;' ,
            'BOB' => 'Bs.' ,
            'BRL' => '&#82;&#36;' ,
            'BSD' => '&#36;' ,
            'BTC' => '&#3647;' ,
            'BTN' => 'Nu.' ,
            'BWP' => 'P' ,
            'BYR' => 'Br' ,
            'BYN' => 'Br' ,
            'BZD' => '&#36;' ,
            'CAD' => '&#36;' ,
            'CDF' => 'Fr' ,
            'CHF' => '&#67;&#72;&#70;' ,
            'CLP' => '&#36;' ,
            'CNY' => '&yen;' ,
            'COP' => '&#36;' ,
            'CRC' => '&#x20a1;' ,
            'CUC' => '&#36;' ,
            'CUP' => '&#36;' ,
            'CVE' => '&#36;' ,
            'CZK' => '&#75;&#269;' ,
            'DJF' => 'Fr' ,
            'DKK' => 'DKK' ,
            'DOP' => 'RD&#36;' ,
            'DZD' => '&#x62f;.&#x62c;' ,
            'EGP' => 'EGP' ,
            'ERN' => 'Nfk' ,
            'ETB' => 'Br' ,
            'EUR' => '&euro;' ,
            'FJD' => '&#36;' ,
            'FKP' => '&pound;' ,
            'GBP' => '&pound;' ,
            'GEL' => '&#x20be;' ,
            'GGP' => '&pound;' ,
            'GHS' => '&#x20b5;' ,
            'GIP' => '&pound;' ,
            'GMD' => 'D' ,
            'GNF' => 'Fr' ,
            'GTQ' => 'Q' ,
            'GYD' => '&#36;' ,
            'HKD' => '&#36;' ,
            'HNL' => 'L' ,
            'HRK' => 'Kn' ,
            'HTG' => 'G' ,
            'HUF' => '&#70;&#116;' ,
            'IDR' => 'Rp' ,
            'ILS' => '&#8362;' ,
            'IMP' => '&pound;' ,
            'INR' => '&#8377;' ,
            'IQD' => '&#x639;.&#x62f;' ,
            'IRR' => '&#xfdfc;' ,
            'IRT' => '&#x062A;&#x0648;&#x0645;&#x0627;&#x0646;' ,
            'ISK' => 'kr.' ,
            'JEP' => '&pound;' ,
            'JMD' => '&#36;' ,
            'JOD' => '&#x62f;.&#x627;' ,
            'JPY' => '&yen;' ,
            'KES' => 'KSh' ,
            'KGS' => '&#x441;&#x43e;&#x43c;' ,
            'KHR' => '&#x17db;' ,
            'KMF' => 'Fr' ,
            'KPW' => '&#x20a9;' ,
            'KRW' => '&#8361;' ,
            'KWD' => '&#x62f;.&#x643;' ,
            'KYD' => '&#36;' ,
            'KZT' => 'KZT' ,
            'LAK' => '&#8365;' ,
            'LBP' => '&#x644;.&#x644;' ,
            'LKR' => '&#xdbb;&#xdd4;' ,
            'LRD' => '&#36;' ,
            'LSL' => 'L' ,
            'LYD' => '&#x644;.&#x62f;' ,
            'MAD' => '&#x62f;.&#x645;.' ,
            'MDL' => 'MDL' ,
            'MGA' => 'Ar' ,
            'MKD' => '&#x434;&#x435;&#x43d;' ,
            'MMK' => 'Ks' ,
            'MNT' => '&#x20ae;' ,
            'MOP' => 'P' ,
            'MRO' => 'UM' ,
            'MUR' => '&#x20a8;' ,
            'MVR' => '.&#x783;' ,
            'MWK' => 'MK' ,
            'MXN' => '&#36;' ,
            'MYR' => '&#82;&#77;' ,
            'MZN' => 'MT' ,
            'NAD' => '&#36;' ,
            'NGN' => '&#8358;' ,
            'NIO' => 'C&#36;' ,
            'NOK' => '&#107;&#114;' ,
            'NPR' => '&#8360;' ,
            'NZD' => '&#36;' ,
            'OMR' => '&#x631;.&#x639;.' ,
            'PAB' => 'B/.' ,
            'PEN' => 'S/.' ,
            'PGK' => 'K' ,
            'PHP' => '&#8369;' ,
            'PKR' => '&#8360;' ,
            'PLN' => '&#122;&#322;' ,
            'PRB' => '&#x440;.' ,
            'PYG' => '&#8370;' ,
            'QAR' => '&#x631;.&#x642;' ,
            'RMB' => '&yen;' ,
            'RON' => 'lei' ,
            'RSD' => '&#x434;&#x438;&#x43d;.' ,
            'RUB' => '&#8381;' ,
            'RWF' => 'Fr' ,
            'SAR' => '&#x631;.&#x633;' ,
            'SBD' => '&#36;' ,
            'SCR' => '&#x20a8;' ,
            'SDG' => '&#x62c;.&#x633;.' ,
            'SEK' => '&#107;&#114;' ,
            'SGD' => '&#36;' ,
            'SHP' => '&pound;' ,
            'SLL' => 'Le' ,
            'SOS' => 'Sh' ,
            'SRD' => '&#36;' ,
            'SSP' => '&pound;' ,
            'STD' => 'Db' ,
            'SYP' => '&#x644;.&#x633;' ,
            'SZL' => 'L' ,
            'THB' => '&#3647;' ,
            'TJS' => '&#x405;&#x41c;' ,
            'TMT' => 'm' ,
            'TND' => '&#x62f;.&#x62a;' ,
            'TOP' => 'T&#36;' ,
            'TRY' => '&#8378;' ,
            'TTD' => '&#36;' ,
            'TWD' => '&#78;&#84;&#36;' ,
            'TZS' => 'Sh' ,
            'UAH' => '&#8372;' ,
            'UGX' => 'UGX' ,
            'USD' => '&#36;' ,
            'UYU' => '&#36;' ,
            'UZS' => 'UZS' ,
            'VEF' => 'Bs F' ,
            'VND' => '&#8363;' ,
            'VUV' => 'Vt' ,
            'WST' => 'T' ,
            'XAF' => 'CFA' ,
            'XCD' => '&#36;' ,
            'XOF' => 'CFA' ,
            'XPF' => 'Fr' ,
            'YER' => '&#xfdfc;' ,
            'ZAR' => '&#82;' ,
            'ZMW' => 'ZK' ,
                )
                ) ;
        $currency_symbol = isset( $symbols[ $currency ] ) ? $symbols[ $currency ] : '' ;

        return apply_filters( 'esf_currency_symbol' , $currency_symbol , $currency ) ;
    }

}


if ( ! function_exists( 'get_esf_countries' ) ) {

    /**
     * Get full list of Countries.
     */
    function get_esf_countries() {
        static $countries ;

        if ( ! isset( $countries ) ) {
            $countries = array_unique(
                    apply_filters(
                            'esf_countries' , array(
                'AF' => esc_html__( 'Afghanistan' , ESF_LOCALE ) ,
                'AX' => esc_html__( '&#197;land Islands' , ESF_LOCALE ) ,
                'AL' => esc_html__( 'Albania' , ESF_LOCALE ) ,
                'DZ' => esc_html__( 'Algeria' , ESF_LOCALE ) ,
                'AS' => esc_html__( 'American Samoa' , ESF_LOCALE ) ,
                'AD' => esc_html__( 'Andorra' , ESF_LOCALE ) ,
                'AO' => esc_html__( 'Angola' , ESF_LOCALE ) ,
                'AI' => esc_html__( 'Anguilla' , ESF_LOCALE ) ,
                'AQ' => esc_html__( 'Antarctica' , ESF_LOCALE ) ,
                'AG' => esc_html__( 'Antigua and Barbuda' , ESF_LOCALE ) ,
                'AR' => esc_html__( 'Argentina' , ESF_LOCALE ) ,
                'AM' => esc_html__( 'Armenia' , ESF_LOCALE ) ,
                'AW' => esc_html__( 'Aruba' , ESF_LOCALE ) ,
                'AU' => esc_html__( 'Australia' , ESF_LOCALE ) ,
                'AT' => esc_html__( 'Austria' , ESF_LOCALE ) ,
                'AZ' => esc_html__( 'Azerbaijan' , ESF_LOCALE ) ,
                'BS' => esc_html__( 'Bahamas' , ESF_LOCALE ) ,
                'BH' => esc_html__( 'Bahrain' , ESF_LOCALE ) ,
                'BD' => esc_html__( 'Bangladesh' , ESF_LOCALE ) ,
                'BB' => esc_html__( 'Barbados' , ESF_LOCALE ) ,
                'BY' => esc_html__( 'Belarus' , ESF_LOCALE ) ,
                'BE' => esc_html__( 'Belgium' , ESF_LOCALE ) ,
                'PW' => esc_html__( 'Belau' , ESF_LOCALE ) ,
                'BZ' => esc_html__( 'Belize' , ESF_LOCALE ) ,
                'BJ' => esc_html__( 'Benin' , ESF_LOCALE ) ,
                'BM' => esc_html__( 'Bermuda' , ESF_LOCALE ) ,
                'BT' => esc_html__( 'Bhutan' , ESF_LOCALE ) ,
                'BO' => esc_html__( 'Bolivia' , ESF_LOCALE ) ,
                'BQ' => esc_html__( 'Bonaire, Saint Eustatius and Saba' , ESF_LOCALE ) ,
                'BA' => esc_html__( 'Bosnia and Herzegovina' , ESF_LOCALE ) ,
                'BW' => esc_html__( 'Botswana' , ESF_LOCALE ) ,
                'BV' => esc_html__( 'Bouvet Island' , ESF_LOCALE ) ,
                'BR' => esc_html__( 'Brazil' , ESF_LOCALE ) ,
                'IO' => esc_html__( 'British Indian Ocean Territory' , ESF_LOCALE ) ,
                'VG' => esc_html__( 'British Virgin Islands' , ESF_LOCALE ) ,
                'BN' => esc_html__( 'Brunei' , ESF_LOCALE ) ,
                'BG' => esc_html__( 'Bulgaria' , ESF_LOCALE ) ,
                'BF' => esc_html__( 'Burkina Faso' , ESF_LOCALE ) ,
                'BI' => esc_html__( 'Burundi' , ESF_LOCALE ) ,
                'KH' => esc_html__( 'Cambodia' , ESF_LOCALE ) ,
                'CM' => esc_html__( 'Cameroon' , ESF_LOCALE ) ,
                'CA' => esc_html__( 'Canada' , ESF_LOCALE ) ,
                'CV' => esc_html__( 'Cape Verde' , ESF_LOCALE ) ,
                'KY' => esc_html__( 'Cayman Islands' , ESF_LOCALE ) ,
                'CF' => esc_html__( 'Central African Republic' , ESF_LOCALE ) ,
                'TD' => esc_html__( 'Chad' , ESF_LOCALE ) ,
                'CL' => esc_html__( 'Chile' , ESF_LOCALE ) ,
                'CN' => esc_html__( 'China' , ESF_LOCALE ) ,
                'CX' => esc_html__( 'Christmas Island' , ESF_LOCALE ) ,
                'CC' => esc_html__( 'Cocos (Keeling) Islands' , ESF_LOCALE ) ,
                'CO' => esc_html__( 'Colombia' , ESF_LOCALE ) ,
                'KM' => esc_html__( 'Comoros' , ESF_LOCALE ) ,
                'CG' => esc_html__( 'Congo (Brazzaville)' , ESF_LOCALE ) ,
                'CD' => esc_html__( 'Congo (Kinshasa)' , ESF_LOCALE ) ,
                'CK' => esc_html__( 'Cook Islands' , ESF_LOCALE ) ,
                'CR' => esc_html__( 'Costa Rica' , ESF_LOCALE ) ,
                'HR' => esc_html__( 'Croatia' , ESF_LOCALE ) ,
                'CU' => esc_html__( 'Cuba' , ESF_LOCALE ) ,
                'CW' => esc_html__( 'Cura&ccedil;ao' , ESF_LOCALE ) ,
                'CY' => esc_html__( 'Cyprus' , ESF_LOCALE ) ,
                'CZ' => esc_html__( 'Czech Republic' , ESF_LOCALE ) ,
                'DK' => esc_html__( 'Denmark' , ESF_LOCALE ) ,
                'DJ' => esc_html__( 'Djibouti' , ESF_LOCALE ) ,
                'DM' => esc_html__( 'Dominica' , ESF_LOCALE ) ,
                'DO' => esc_html__( 'Dominican Republic' , ESF_LOCALE ) ,
                'EC' => esc_html__( 'Ecuador' , ESF_LOCALE ) ,
                'EG' => esc_html__( 'Egypt' , ESF_LOCALE ) ,
                'SV' => esc_html__( 'El Salvador' , ESF_LOCALE ) ,
                'GQ' => esc_html__( 'Equatorial Guinea' , ESF_LOCALE ) ,
                'ER' => esc_html__( 'Eritrea' , ESF_LOCALE ) ,
                'EE' => esc_html__( 'Estonia' , ESF_LOCALE ) ,
                'ET' => esc_html__( 'Ethiopia' , ESF_LOCALE ) ,
                'FK' => esc_html__( 'Falkland Islands' , ESF_LOCALE ) ,
                'FO' => esc_html__( 'Faroe Islands' , ESF_LOCALE ) ,
                'FJ' => esc_html__( 'Fiji' , ESF_LOCALE ) ,
                'FI' => esc_html__( 'Finland' , ESF_LOCALE ) ,
                'FR' => esc_html__( 'France' , ESF_LOCALE ) ,
                'GF' => esc_html__( 'French Guiana' , ESF_LOCALE ) ,
                'PF' => esc_html__( 'French Polynesia' , ESF_LOCALE ) ,
                'TF' => esc_html__( 'French Southern Territories' , ESF_LOCALE ) ,
                'GA' => esc_html__( 'Gabon' , ESF_LOCALE ) ,
                'GM' => esc_html__( 'Gambia' , ESF_LOCALE ) ,
                'GE' => esc_html__( 'Georgia' , ESF_LOCALE ) ,
                'DE' => esc_html__( 'Germany' , ESF_LOCALE ) ,
                'GH' => esc_html__( 'Ghana' , ESF_LOCALE ) ,
                'GI' => esc_html__( 'Gibraltar' , ESF_LOCALE ) ,
                'GR' => esc_html__( 'Greece' , ESF_LOCALE ) ,
                'GL' => esc_html__( 'Greenland' , ESF_LOCALE ) ,
                'GD' => esc_html__( 'Grenada' , ESF_LOCALE ) ,
                'GP' => esc_html__( 'Guadeloupe' , ESF_LOCALE ) ,
                'GU' => esc_html__( 'Guam' , ESF_LOCALE ) ,
                'GT' => esc_html__( 'Guatemala' , ESF_LOCALE ) ,
                'GG' => esc_html__( 'Guernsey' , ESF_LOCALE ) ,
                'GN' => esc_html__( 'Guinea' , ESF_LOCALE ) ,
                'GW' => esc_html__( 'Guinea-Bissau' , ESF_LOCALE ) ,
                'GY' => esc_html__( 'Guyana' , ESF_LOCALE ) ,
                'HT' => esc_html__( 'Haiti' , ESF_LOCALE ) ,
                'HM' => esc_html__( 'Heard Island and McDonald Islands' , ESF_LOCALE ) ,
                'HN' => esc_html__( 'Honduras' , ESF_LOCALE ) ,
                'HK' => esc_html__( 'Hong Kong' , ESF_LOCALE ) ,
                'HU' => esc_html__( 'Hungary' , ESF_LOCALE ) ,
                'IS' => esc_html__( 'Iceland' , ESF_LOCALE ) ,
                'IN' => esc_html__( 'India' , ESF_LOCALE ) ,
                'ID' => esc_html__( 'Indonesia' , ESF_LOCALE ) ,
                'IR' => esc_html__( 'Iran' , ESF_LOCALE ) ,
                'IQ' => esc_html__( 'Iraq' , ESF_LOCALE ) ,
                'IE' => esc_html__( 'Ireland' , ESF_LOCALE ) ,
                'IM' => esc_html__( 'Isle of Man' , ESF_LOCALE ) ,
                'IL' => esc_html__( 'Israel' , ESF_LOCALE ) ,
                'IT' => esc_html__( 'Italy' , ESF_LOCALE ) ,
                'CI' => esc_html__( 'Ivory Coast' , ESF_LOCALE ) ,
                'JM' => esc_html__( 'Jamaica' , ESF_LOCALE ) ,
                'JP' => esc_html__( 'Japan' , ESF_LOCALE ) ,
                'JE' => esc_html__( 'Jersey' , ESF_LOCALE ) ,
                'JO' => esc_html__( 'Jordan' , ESF_LOCALE ) ,
                'KZ' => esc_html__( 'Kazakhstan' , ESF_LOCALE ) ,
                'KE' => esc_html__( 'Kenya' , ESF_LOCALE ) ,
                'KI' => esc_html__( 'Kiribati' , ESF_LOCALE ) ,
                'KW' => esc_html__( 'Kuwait' , ESF_LOCALE ) ,
                'KG' => esc_html__( 'Kyrgyzstan' , ESF_LOCALE ) ,
                'LA' => esc_html__( 'Laos' , ESF_LOCALE ) ,
                'LV' => esc_html__( 'Latvia' , ESF_LOCALE ) ,
                'LB' => esc_html__( 'Lebanon' , ESF_LOCALE ) ,
                'LS' => esc_html__( 'Lesotho' , ESF_LOCALE ) ,
                'LR' => esc_html__( 'Liberia' , ESF_LOCALE ) ,
                'LY' => esc_html__( 'Libya' , ESF_LOCALE ) ,
                'LI' => esc_html__( 'Liechtenstein' , ESF_LOCALE ) ,
                'LT' => esc_html__( 'Lithuania' , ESF_LOCALE ) ,
                'LU' => esc_html__( 'Luxembourg' , ESF_LOCALE ) ,
                'MO' => esc_html__( 'Macao S.A.R., China' , ESF_LOCALE ) ,
                'MK' => esc_html__( 'Macedonia' , ESF_LOCALE ) ,
                'MG' => esc_html__( 'Madagascar' , ESF_LOCALE ) ,
                'MW' => esc_html__( 'Malawi' , ESF_LOCALE ) ,
                'MY' => esc_html__( 'Malaysia' , ESF_LOCALE ) ,
                'MV' => esc_html__( 'Maldives' , ESF_LOCALE ) ,
                'ML' => esc_html__( 'Mali' , ESF_LOCALE ) ,
                'MT' => esc_html__( 'Malta' , ESF_LOCALE ) ,
                'MH' => esc_html__( 'Marshall Islands' , ESF_LOCALE ) ,
                'MQ' => esc_html__( 'Martinique' , ESF_LOCALE ) ,
                'MR' => esc_html__( 'Mauritania' , ESF_LOCALE ) ,
                'MU' => esc_html__( 'Mauritius' , ESF_LOCALE ) ,
                'YT' => esc_html__( 'Mayotte' , ESF_LOCALE ) ,
                'MX' => esc_html__( 'Mexico' , ESF_LOCALE ) ,
                'FM' => esc_html__( 'Micronesia' , ESF_LOCALE ) ,
                'MD' => esc_html__( 'Moldova' , ESF_LOCALE ) ,
                'MC' => esc_html__( 'Monaco' , ESF_LOCALE ) ,
                'MN' => esc_html__( 'Mongolia' , ESF_LOCALE ) ,
                'ME' => esc_html__( 'Montenegro' , ESF_LOCALE ) ,
                'MS' => esc_html__( 'Montserrat' , ESF_LOCALE ) ,
                'MA' => esc_html__( 'Morocco' , ESF_LOCALE ) ,
                'MZ' => esc_html__( 'Mozambique' , ESF_LOCALE ) ,
                'MM' => esc_html__( 'Myanmar' , ESF_LOCALE ) ,
                'NA' => esc_html__( 'Namibia' , ESF_LOCALE ) ,
                'NR' => esc_html__( 'Nauru' , ESF_LOCALE ) ,
                'NP' => esc_html__( 'Nepal' , ESF_LOCALE ) ,
                'NL' => esc_html__( 'Netherlands' , ESF_LOCALE ) ,
                'NC' => esc_html__( 'New Caledonia' , ESF_LOCALE ) ,
                'NZ' => esc_html__( 'New Zealand' , ESF_LOCALE ) ,
                'NI' => esc_html__( 'Nicaragua' , ESF_LOCALE ) ,
                'NE' => esc_html__( 'Niger' , ESF_LOCALE ) ,
                'NG' => esc_html__( 'Nigeria' , ESF_LOCALE ) ,
                'NU' => esc_html__( 'Niue' , ESF_LOCALE ) ,
                'NF' => esc_html__( 'Norfolk Island' , ESF_LOCALE ) ,
                'MP' => esc_html__( 'Northern Mariana Islands' , ESF_LOCALE ) ,
                'KP' => esc_html__( 'North Korea' , ESF_LOCALE ) ,
                'NO' => esc_html__( 'Norway' , ESF_LOCALE ) ,
                'OM' => esc_html__( 'Oman' , ESF_LOCALE ) ,
                'PK' => esc_html__( 'Pakistan' , ESF_LOCALE ) ,
                'PS' => esc_html__( 'Palestinian Territory' , ESF_LOCALE ) ,
                'PA' => esc_html__( 'Panama' , ESF_LOCALE ) ,
                'PG' => esc_html__( 'Papua New Guinea' , ESF_LOCALE ) ,
                'PY' => esc_html__( 'Paraguay' , ESF_LOCALE ) ,
                'PE' => esc_html__( 'Peru' , ESF_LOCALE ) ,
                'PH' => esc_html__( 'Philippines' , ESF_LOCALE ) ,
                'PN' => esc_html__( 'Pitcairn' , ESF_LOCALE ) ,
                'PL' => esc_html__( 'Poland' , ESF_LOCALE ) ,
                'PT' => esc_html__( 'Portugal' , ESF_LOCALE ) ,
                'PR' => esc_html__( 'Puerto Rico' , ESF_LOCALE ) ,
                'QA' => esc_html__( 'Qatar' , ESF_LOCALE ) ,
                'RE' => esc_html__( 'Reunion' , ESF_LOCALE ) ,
                'RO' => esc_html__( 'Romania' , ESF_LOCALE ) ,
                'RU' => esc_html__( 'Russia' , ESF_LOCALE ) ,
                'RW' => esc_html__( 'Rwanda' , ESF_LOCALE ) ,
                'BL' => esc_html__( 'Saint Barth&eacute;lemy' , ESF_LOCALE ) ,
                'SH' => esc_html__( 'Saint Helena' , ESF_LOCALE ) ,
                'KN' => esc_html__( 'Saint Kitts and Nevis' , ESF_LOCALE ) ,
                'LC' => esc_html__( 'Saint Lucia' , ESF_LOCALE ) ,
                'MF' => esc_html__( 'Saint Martin (French part)' , ESF_LOCALE ) ,
                'SX' => esc_html__( 'Saint Martin (Dutch part)' , ESF_LOCALE ) ,
                'PM' => esc_html__( 'Saint Pierre and Miquelon' , ESF_LOCALE ) ,
                'VC' => esc_html__( 'Saint Vincent and the Grenadines' , ESF_LOCALE ) ,
                'SM' => esc_html__( 'San Marino' , ESF_LOCALE ) ,
                'ST' => esc_html__( 'S&atilde;o Tom&eacute; and Pr&iacute;ncipe' , ESF_LOCALE ) ,
                'SA' => esc_html__( 'Saudi Arabia' , ESF_LOCALE ) ,
                'SN' => esc_html__( 'Senegal' , ESF_LOCALE ) ,
                'RS' => esc_html__( 'Serbia' , ESF_LOCALE ) ,
                'SC' => esc_html__( 'Seychelles' , ESF_LOCALE ) ,
                'SL' => esc_html__( 'Sierra Leone' , ESF_LOCALE ) ,
                'SG' => esc_html__( 'Singapore' , ESF_LOCALE ) ,
                'SK' => esc_html__( 'Slovakia' , ESF_LOCALE ) ,
                'SI' => esc_html__( 'Slovenia' , ESF_LOCALE ) ,
                'SB' => esc_html__( 'Solomon Islands' , ESF_LOCALE ) ,
                'SO' => esc_html__( 'Somalia' , ESF_LOCALE ) ,
                'ZA' => esc_html__( 'South Africa' , ESF_LOCALE ) ,
                'GS' => esc_html__( 'South Georgia/Sandwich Islands' , ESF_LOCALE ) ,
                'KR' => esc_html__( 'South Korea' , ESF_LOCALE ) ,
                'SS' => esc_html__( 'South Sudan' , ESF_LOCALE ) ,
                'ES' => esc_html__( 'Spain' , ESF_LOCALE ) ,
                'LK' => esc_html__( 'Sri Lanka' , ESF_LOCALE ) ,
                'SD' => esc_html__( 'Sudan' , ESF_LOCALE ) ,
                'SR' => esc_html__( 'Suriname' , ESF_LOCALE ) ,
                'SJ' => esc_html__( 'Svalbard and Jan Mayen' , ESF_LOCALE ) ,
                'SZ' => esc_html__( 'Swaziland' , ESF_LOCALE ) ,
                'SE' => esc_html__( 'Sweden' , ESF_LOCALE ) ,
                'CH' => esc_html__( 'Switzerland' , ESF_LOCALE ) ,
                'SY' => esc_html__( 'Syria' , ESF_LOCALE ) ,
                'TW' => esc_html__( 'Taiwan' , ESF_LOCALE ) ,
                'TJ' => esc_html__( 'Tajikistan' , ESF_LOCALE ) ,
                'TZ' => esc_html__( 'Tanzania' , ESF_LOCALE ) ,
                'TH' => esc_html__( 'Thailand' , ESF_LOCALE ) ,
                'TL' => esc_html__( 'Timor-Leste' , ESF_LOCALE ) ,
                'TG' => esc_html__( 'Togo' , ESF_LOCALE ) ,
                'TK' => esc_html__( 'Tokelau' , ESF_LOCALE ) ,
                'TO' => esc_html__( 'Tonga' , ESF_LOCALE ) ,
                'TT' => esc_html__( 'Trinidad and Tobago' , ESF_LOCALE ) ,
                'TN' => esc_html__( 'Tunisia' , ESF_LOCALE ) ,
                'TR' => esc_html__( 'Turkey' , ESF_LOCALE ) ,
                'TM' => esc_html__( 'Turkmenistan' , ESF_LOCALE ) ,
                'TC' => esc_html__( 'Turks and Caicos Islands' , ESF_LOCALE ) ,
                'TV' => esc_html__( 'Tuvalu' , ESF_LOCALE ) ,
                'UG' => esc_html__( 'Uganda' , ESF_LOCALE ) ,
                'UA' => esc_html__( 'Ukraine' , ESF_LOCALE ) ,
                'AE' => esc_html__( 'United Arab Emirates' , ESF_LOCALE ) ,
                'GB' => esc_html__( 'United Kingdom (UK)' , ESF_LOCALE ) ,
                'US' => esc_html__( 'United States (US)' , ESF_LOCALE ) ,
                'UM' => esc_html__( 'United States (US) Minor Outlying Islands' , ESF_LOCALE ) ,
                'VI' => esc_html__( 'United States (US) Virgin Islands' , ESF_LOCALE ) ,
                'UY' => esc_html__( 'Uruguay' , ESF_LOCALE ) ,
                'UZ' => esc_html__( 'Uzbekistan' , ESF_LOCALE ) ,
                'VU' => esc_html__( 'Vanuatu' , ESF_LOCALE ) ,
                'VA' => esc_html__( 'Vatican' , ESF_LOCALE ) ,
                'VE' => esc_html__( 'Venezuela' , ESF_LOCALE ) ,
                'VN' => esc_html__( 'Vietnam' , ESF_LOCALE ) ,
                'WF' => esc_html__( 'Wallis and Futuna' , ESF_LOCALE ) ,
                'EH' => esc_html__( 'Western Sahara' , ESF_LOCALE ) ,
                'WS' => esc_html__( 'Samoa' , ESF_LOCALE ) ,
                'YE' => esc_html__( 'Yemen' , ESF_LOCALE ) ,
                'ZM' => esc_html__( 'Zambia' , ESF_LOCALE ) ,
                'ZW' => esc_html__( 'Zimbabwe' , ESF_LOCALE ) ,
                            )
                    )
                    ) ;
        }

        return $countries ;
    }

}

if ( ! function_exists( 'esf_get_drop_down_values' ) ) {

    /**
     * Get dropdown values for calendar tab
     */
    function esf_get_drop_down_values( $index ) {
        global $wpdb ;
        switch ( $index ) {
            case 'range_type':
                $value = array(
                    '1'         => 'Date Range' ,
                    '2'         => 'Range of Month(s)' ,
                    '3'         => 'Range of Week(s)' ,
                    '4'         => 'Range of Day(s)' ,
                    '5'         => 'Time Range(All Days)' ,
                    '6'         => 'Date Range with Time' ,
                    'Monday'    => 'Monday' ,
                    'Tuesday'   => 'Tuesday' ,
                    'Wednesday' => 'Wednesday' ,
                    'Thursday'  => 'Thursday' ,
                    'Friday'    => 'Friday' ,
                    'Saturday'  => 'Saturday' ,
                    'Sunday'    => 'Sunday'
                        ) ;
                break ;
            case 'days':
                $value = array(
                    '0' => 'Sun' ,
                    '1' => 'Mon' ,
                    '2' => 'Tue' ,
                    '3' => 'Wed' ,
                    '4' => 'Thu' ,
                    '5' => 'Fri' ,
                    '6' => 'Sat' ,
                        ) ;
                break ;
            case 'months':
                $value = array(
                    '01' => 'January' ,
                    '02' => 'February' ,
                    '03' => 'March' ,
                    '04' => 'April' ,
                    '05' => 'May' ,
                    '06' => 'June' ,
                    '07' => 'July' ,
                    '08' => 'August' ,
                    '09' => 'September' ,
                    '10' => 'October' ,
                    '11' => 'November' ,
                    '12' => 'December' ,
                        ) ;
                break ;
            case 'operator':
                $value = array(
                    '1' => '+' ,
                    '2' => '-' ,
                    '3' => '*' ,
                    '4' => '/' ,
                        ) ;
                break ;
            case 'weeks':
                for ( $i = 1 ; $i <= 52 ; $i ++ ) {
                    $value[ $i ] = 'Week' . $i ;
                }
                break ;
            default :
                $value = '' ;
                break ;
        }
        return $value ;
    }

}